package model;
// Generated Sep 28, 2024 10:31:33 AM by Hibernate Tools 4.3.1

import dao.LoginDAO;
import java.io.IOException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

/**
 * Admin generated by hbm2java
 */
@ManagedBean(name = "admin")
@SessionScoped
public class Admin implements java.io.Serializable {

    private String adminId;
    private String password;

    public String validateAdmin() {
        LoginDAO uDao = new LoginDAO();
        List<Admin> us = uDao.getBy(adminId, password);
        if (us != null && !us.isEmpty()) {
            adminId = us.get(0).adminId;
            password = us.get(0).password;
            return "dashboard";
        } else {
            FacesContext.getCurrentInstance().addMessage(null,
                    new javax.faces.application.FacesMessage("Invalid username or password"));
            return "index";
        }
    }

    public void logout() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        if (session != null) {
            session.invalidate();
        }
        try {
            context.getExternalContext().redirect("index.xhtml");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public Admin() {
    }

    public Admin(String adminId, String password) {
        this.adminId = adminId;
        this.password = password;
    }

    public String getAdminId() {
        return this.adminId;
    }

    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
